In [339]:
#Importation des bibliotheques

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

 1- Les données

In [340]:
#importation des données

df= pd.read_csv("aids.csv",sep=';', encoding='ISO-8859-1')

In [341]:
df.head()

,Pays,Année,mort_orphelin,mort_adulte,mort_toutAge,mort_enfant,mort_femmeAdulte,mort_hommeAdulte,\nprevalence_adulte,\nPrevalence.jeuneHomme,...,new_infection_hommeAdulte,new_infection_femmeAdulte,new_infection_enfant,new_infection_toutAge,new_infection_Adulte,New_ Infection.\nIncidence_Rate_Among_Adults,personnes_vivant_avec.Total,adulte_homme_vivant_avec,adulte_femme_vivant_avec,enfant_vivant_avec
0,Afghanistan,1990.0,100.0,100.0,500,100.0,100.0,100.0,0.1,0.1,...,100.0,100.0,100.0,100.0,100.0,0.01,700.0,500.0,100.0,100.0
1,Afghanistan,1991.0,100.0,100.0,500,100.0,100.0,100.0,0.1,0.1,...,100.0,100.0,100.0,100.0,100.0,0.01,500.0,500.0,100.0,100.0
2,Afghanistan,1992.0,100.0,100.0,500,100.0,100.0,100.0,0.1,0.1,...,100.0,100.0,100.0,100.0,100.0,0.01,500.0,500.0,200.0,100.0
3,Afghanistan,1993.0,200.0,100.0,600,100.0,100.0,100.0,0.1,0.1,...,100.0,100.0,100.0,200.0,200.0,0.01,1000.0,500.0,200.0,100.0
4,Afghanistan,1994.0,200.0,100.0,600,100.0,100.0,100.0,0.1,0.1,...,100.0,100.0,100.0,200.0,200.0,0.01,1000.0,500.0,200.0,100.0

In [342]:
nb_row = df.shape[0]
print("nombre total de ligne:", nb_row )

nombre total de ligne: 2761

In [343]:
print("les colonnes de notre jeu de données:")
list(df)

les colonnes de notre jeu de données:

['Pays',
 'Année',
 'mort_orphelin',
 'mort_adulte',
 'mort_toutAge',
 'mort_enfant',
 'mort_femmeAdulte',
 'mort_hommeAdulte',
 '\nprevalence_adulte',
 ' \nPrevalence.jeuneHomme',
 ' \nPrevalence.jeuneFemme',
 'new_infection_jeuneAdulte',
 'new_infection_hommeAdulte',
 'new_infection_femmeAdulte',
 'new_infection_enfant',
 'new_infection_toutAge',
 'new_infection_Adulte',
 'New_ Infection.\nIncidence_Rate_Among_Adults',
 'personnes_vivant_avec.Total',
 'adulte_homme_vivant_avec',
 'adulte_femme_vivant_avec',
 'enfant_vivant_avec']

In [344]:
 df.describe()

,Année,mort_orphelin,mort_adulte,mort_toutAge,mort_enfant,mort_femmeAdulte,mort_hommeAdulte,\nprevalence_adulte,\nPrevalence.jeuneHomme,\nPrevalence.jeuneFemme,...,new_infection_hommeAdulte,new_infection_femmeAdulte,new_infection_enfant,new_infection_toutAge,new_infection_Adulte,New_ Infection.\nIncidence_Rate_Among_Adults,personnes_vivant_avec.Total,adulte_homme_vivant_avec,adulte_femme_vivant_avec,enfant_vivant_avec
count,2759.000000,2.759000e+03,2759.000000,2.761000e+03,2759.000000,2759.00000,2759.000000,2759.00000,2759.000000,2759.000000,...,2759.000000,2759.000000,2759.000000,2759.000000,2759.000000,2759.000000,2.759000e+03,2.759000e+03,2.759000e+03,2759.000000
mean,2005.000000,1.042936e+05,7755.164915,1.223039e+05,2498.767669,4134.03407,3710.982240,2.60087,0.681080,1.754295,...,7341.210584,9440.376948,3762.812613,20377.056905,16714.570497,2.446709,2.295033e+05,8.879431e+04,1.207789e+05,20145.487495
std,8.945893,2.437087e+05,18358.408671,2.785213e+05,5395.969671,10180.29161,8376.379071,5.01104,1.246115,3.676298,...,18184.161485,26294.247159,8363.538494,51338.602880,44282.254397,5.475743,6.140099e+05,2.227659e+05,3.533831e+05,45998.105241
min,1990.000000,1.000000e+02,100.000000,0.000000e+00,100.000000,100.00000,100.000000,0.10000,0.100000,0.100000,...,100.000000,100.000000,100.000000,100.000000,100.000000,0.010000,1.000000e+02,1.000000e+02,1.000000e+02,100.000000
25%,1997.000000,1.200000e+03,200.000000,2.000000e+03,100.000000,100.00000,100.000000,0.10000,0.100000,0.100000,...,500.000000,500.000000,100.000000,1000.000000,1000.000000,0.140000,7.900000e+03,4.300000e+03,2.700000e+03,200.000000
50%,2005.000000,1.200000e+04,1100.000000,1.560000e+04,500.000000,500.00000,1000.000000,0.60000,0.100000,0.200000,...,1600.000000,1100.000000,500.000000,3600.000000,2900.000000,0.400000,3.700000e+04,1.700000e+04,1.300000e+04,1700.000000
75%,2013.000000,6.600000e+04,5000.000000,7.910000e+04,1700.000000,2400.00000,2800.000000,2.10000,0.600000,1.400000,...,5500.000000,5400.000000,2500.000000,13000.000000,11000.000000,1.860000,1.400000e+05,6.300000e+04,6.650000e+04,13000.000000
max,2020.000000,1.800000e+06,220000.000000,2.075000e+06,49000.000000,130000.00000,92000.000000,28.90000,8.900000,23.900000,...,190000.000000,280000.000000,73000.000000,520000.000000,470000.000000,45.110000,7.800000e+06,2.700000e+06,4.800000e+06,380000.000000

2- Nettoyage

In [345]:
df.info()
#on constate qu'il y'a des lignes vides dans notre jeu de données

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2761 entries, 0 to 2760
Data columns (total 22 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Pays                                         2759 non-null   object
 1   Année                                        2759 non-null   float64
 2   mort_orphelin                                2759 non-null   float64
 3   mort_adulte                                  2759 non-null   float64
 4   mort_toutAge                                 2761 non-null   int64
 5   mort_enfant                                  2759 non-null   float64
 6   mort_femmeAdulte                             2759 non-null   float64
 7   mort_hommeAdulte                             2759 non-null   float64
 8
prevalence_adulte                           2759 non-null   float64
 9
Prevalence.jeuneHomme                      2759 non-null   float64
 10
Prevalence.jeuneFemme                      2759 non-null   float64
 11  new_infection_jeuneAdulte                    2759 non-null   float64
 12  new_infection_hommeAdulte                    2759 non-null   float64
 13  new_infection_femmeAdulte                    2759 non-null   float64
 14  new_infection_enfant                         2759 non-null   float64
 15  new_infection_toutAge                        2759 non-null   float64
 16  new_infection_Adulte                         2759 non-null   float64
 17  New_ Infection.
Incidence_Rate_Among_Adults  2759 non-null   float64
 18  personnes_vivant_avec.Total                  2759 non-null   float64
 19  adulte_homme_vivant_avec                     2759 non-null   float64
 20  adulte_femme_vivant_avec                     2759 non-null   float64
 21  enfant_vivant_avec                           2759 non-null   float64
dtypes: float64(20), int64(1), object(1)
memory usage: 474.7+ KB

In [346]:
# Pour voir les lignes vides
print(df.isnull().sum())

Pays                                            2
Année                                           2
mort_orphelin                                   2
mort_adulte                                     2
mort_toutAge                                    0
mort_enfant                                     2
mort_femmeAdulte                                2
mort_hommeAdulte                                2
\nprevalence_adulte                             2
 \nPrevalence.jeuneHomme                        2
 \nPrevalence.jeuneFemme                        2
new_infection_jeuneAdulte                       2
new_infection_hommeAdulte                       2
new_infection_femmeAdulte                       2
new_infection_enfant                            2
new_infection_toutAge                           2
new_infection_Adulte                            2
New_ Infection.\nIncidence_Rate_Among_Adults    2
personnes_vivant_avec.Total                     2
adulte_homme_vivant_avec                        2
adulte_femme_vivant_avec                        2
enfant_vivant_avec                              2
dtype: int64

In [347]:
# pour supprimer toutes les ignes qui ont des colonnes vides
df = df.dropna(axis=0, how='any')

In [348]:
print(df.isnull().sum())

Pays                                            0
Année                                           0
mort_orphelin                                   0
mort_adulte                                     0
mort_toutAge                                    0
mort_enfant                                     0
mort_femmeAdulte                                0
mort_hommeAdulte                                0
\nprevalence_adulte                             0
 \nPrevalence.jeuneHomme                        0
 \nPrevalence.jeuneFemme                        0
new_infection_jeuneAdulte                       0
new_infection_hommeAdulte                       0
new_infection_femmeAdulte                       0
new_infection_enfant                            0
new_infection_toutAge                           0
new_infection_Adulte                            0
New_ Infection.\nIncidence_Rate_Among_Adults    0
personnes_vivant_avec.Total                     0
adulte_homme_vivant_avec                        0
adulte_femme_vivant_avec                        0
enfant_vivant_avec                              0
dtype: int64

In [349]:
#Sélectionne les variables qu'on veut utiliser pour la prédiction
#Prévalence adulte = (Nombre total d'adultes vivant avec la maladie / Population adulte totale) x 100

X = df[['Année', 'mort_toutAge', 'new_infection_toutAge']]
y = df['\nprevalence_adulte']

In [350]:
# Créer un modèle de régression linéaire
lr_model = LinearRegression()

In [351]:
# Entraîner le modèle sur les données d'entraînement
lr_model.fit(X, y)

LinearRegression()

In [352]:
# Faire des prédictions sur de nouvelles données
nouvelles_donnees = [[2022, 1000, 2000]]
prediction = lr_model.predict(nouvelles_donnees)

print(prediction)

#on observe qu'en 2022, il aura des personnes qui vivront avec la maladie

[1.56129335]

C:\Users\dilan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [353]:

# faire des prédictions pour chaque pays en 2022
X_2022 = ... # les données de prédiction pour 2022 pour chaque pays
y_pred_2022 = model.predict(X_2022)

# trouver le pays avec la valeur de mortalité la plus élevée
#max_mortality_country = data.loc[y_pred_2022.argmax(), 'Pays']
print("Le pays avec la valeur de mortalité la plus élevée en 2022 est : ", max_mortality_country)

C:\Users\dilan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got scalar array instead:
array=Ellipsis.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
# créer les ensembles d'entraînement et de test
X_train = df.drop(["Pays", "Année", "mort_toutAge"], axis=1)[:30] # les 30 premières années pour l'entraînement
y_train = df["mort_toutAge"][:30]
X_test = df.drop(["Pays", "Année", "mort_toutAge"], axis=1)[30:] # les années restantes pour le test
y_test = df["mort_toutAge"][30:]

# entraîner le modèle
model = LinearRegression()
model.fit(X_train, y_train)
# faire des prédictions pour chaque pays en 2022
X_2022 = df[df["Année"]==2022].drop(["Pays", "Année", "mort_toutAge"], axis=1)
y_pred_2022 = model.predict(X_2022)

# trouver le pays avec la valeur de mortalité la plus élevée
pays_plus_de_morts_2022 = df.loc[df["Année"]==2022].iloc[y_pred_2022.argmax()]["Pays"]
print("Le pays avec la valeur de mortalité la plus élevée en 2022 est : ", pays_plus_de_morts_2022)

In [ ]:
X = df.drop(["Pays", "Année", "mort_toutAge"], axis=1) # variables indépendantes
y = df["mort_toutAge"] # variable dépendante
model = LinearRegression().fit(X, y)

In [ ]:
X_2022 = df[df["Année"]==2022].drop(["Pays", "Année", "mort_toutAge"], axis=1) # les données de prédiction pour 2022 pour chaque pays
y_pred_2022 = model.predict(X_2022)

In [ ]:
df.groupby(['Année', 'Pays'])['mort_toutAge'].idxmax()

In [ ]:
df = df[df["Année"] <= 2020]

In [ ]:
X = df.drop(["Pays", "Année", "mort_toutAge"], axis=1)
y = df["mort_toutAge"]

In [ ]:
X = df.drop(["Pays", "Année", "mort_toutAge"], axis=1)
y = df["mort_toutAge"]

In [ ]:
X_2022 = df[df["Année"]==2022].drop(["Pays", "Année", "mort_toutAge"], axis=1)

In [ ]:
#y_pred_2022 = model.predict(X_2022)

In [ ]:
print(X_2022.shape)

In [ ]:
df.groupby(['Année', 'Pays'])['mort_toutAge'].idxmax()

In [ ]:
df[df["Année"]==2020].sort_values("mort_toutAge", ascending=False).iloc[0]["Pays"]

In [ ]:
X = df[['Année', 'mort_toutAge', 'new_infection_toutAge']]
y = df['\nprevalence_adulte']
lr_model = LinearRegression()
lr_model.fit(X, y)
nouvelles_donnees = [[2022, 1000, 2000]]
prediction = lr_model.predict(nouvelles_donnees)

print(prediction)